version: "3.9"
services:
  ejemploglobal:
    build: .
    ports:
      - "3000:3000"
    links: 
      - ejemplo
  ejemplo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gamer
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
      #mysql /var/lib/mysql
      #postgres /var/lib/postgresql/data
volumes:
  mongo-data:
